-- Migration number: 0001 	 2025-06-19T18:13:02.648Z
CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT,
    completed INTEGER DEFAULT 0 NOT NULL,
    due_date DATETIME
);
